# Generated by Django 4.2.1 on 2026-02-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('inquiry_type', models.CharField(choices=[('Attach your EV', 'Attach your EV'), ('Work with driver partner', 'Work with driver partner'), ('Media Enquiry', 'Media Enquiry'), ('None of the Above', 'None of the Above')], max_length=100, verbose_name='Inquiry Type')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('found_us', models.CharField(choices=[('Google Search', 'Google Search'), ('Website', 'Website'), ('Social Media', 'Social Media'), ('Reference', 'Reference'), ('Saw Eonmove Vehicle on Road', 'Saw Eonmove Vehicle on Road'), ('Other', 'Other')], max_length=100, verbose_name='How did you find EonMove?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Partnership Submission',
                'verbose_name_plural': 'Partnership Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquirySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('organisation', models.CharField(max_length=300, verbose_name='Organisation')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Enquiry Submission',
                'verbose_name_plural': 'Enquiry Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
